<?php

require_once 'PHPUnit/Framework.php';

require_once CLASS_PATH.'/AnnoLoader/Dependency/Type/Class.php';
require_once CLASS_PATH.'/AnnoLoader/Dependency/Type/Exception.php';
require_once CLASS_PATH.'/AnnoLoader/Class/Mapper.php';

/**
 * Test class for AnnoLoader_Dependency_Type_Namespace.
 * Generated by PHPUnit on 2011-01-17 at 14:08:24.
 */
class AnnoLoader_Dependency_Type_NamespaceTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Dependency_Type_Namespace
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new AnnoLoader_Dependency_Type_Namespace;

		$this->object->setFilesList(array
		(
			JS_PATH.'/DependencyTypeNamespace/ex/data/Store.js' => true,
			JS_PATH.'/DependencyTypeNamespace/ex/data/Record.js' => true,
			JS_PATH.'/DependencyTypeNamespace/ux/data/Store.js' => true,
			JS_PATH.'/DependencyTypeNamespace/ux/data/Record.js' => true,
		));

		$this->object->setBasePath(JS_PATH.'/DependencyTypeNamespace');
		$this->object->setExtension('js');
		$this->object->setNamespace(array
		(
			'Ext.ex'	=> 'ex',
			'Ext.ux'	=> 'ux',
		));
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers AnnoLoader_Dependency_Type_Namespace::getFiles
	 */
	public function testGetFiles()
	{
		$dependency = 'Ext.ex';
		$this->assertEquals(
			array
			(
				JS_PATH.'/DependencyTypeNamespace/ex/data/Store.js',
				JS_PATH.'/DependencyTypeNamespace/ex/data/Record.js',
			),
			$this->object->getFiles($dependency, 'test'
		));
		$dependency = 'Ext.ux';
		$this->assertEquals(
			array
			(
				JS_PATH.'/DependencyTypeNamespace/ux/data/Store.js',
				JS_PATH.'/DependencyTypeNamespace/ux/data/Record.js',
			),
			$this->object->getFiles($dependency, 'test'
		));
	}

	/**
	 * @covers AnnoLoader_Dependency_Type_Namespace::getFiles
	 * @expectedException AnnoLoader_Dependency_Type_Exception
	 */
	public function testGetFilesException()
	{
		$dependency = 'Ext.nonExistig';
		$this->object->getFiles($dependency, 'test');
	}
}

?>
