<?php

require_once 'PHPUnit/Framework.php';

require_once CLASS_PATH.'/AnnoLoader/Directory/Iterator.php';

/**
 * Test class for AnnoLoader_Directory_Iterator.
 * Generated by PHPUnit on 2011-01-14 at 14:07:53.
 */
class AnnoLoader_Directory_IteratorTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Directory_Iterator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new AnnoLoader_Directory_Iterator;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testGet() 
	{
		$expectedResult = array
		(
			JS_PATH.'/DirectoryIterator/ex/form/Panel.js' => null,
			JS_PATH.'/DirectoryIterator/ex/grid/Panel.js' => null,
		);
		$this->assertEquals($expectedResult, $this->object->get(JS_PATH.'/DirectoryIterator/ex', 'js'));

		$expectedResult = array
		(
			JS_PATH.'/DirectoryIterator/ux/grid/Filters/String.js' => null,
		);
		$this->assertEquals($expectedResult, $this->object->get(JS_PATH.'/DirectoryIterator/ux', 'js'));
	}

	public function testGetEmpty()
	{
		$paths = $this->object->get(JS_PATH.'/DirectoryIterator/empty', 'js');
		$this->assertTrue(empty($paths));
	}

}

?>
