<?php

require_once 'PHPUnit/Framework.php';

require_once CLASS_PATH.'/AnnoLoader/Namespace/Map.php';

/**
 * Test class for AnnoLoader_Namespace_Map.
 * Generated by PHPUnit on 2011-01-14 at 15:41:30.
 */
class AnnoLoader_Namespace_MapTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Namespace_Map
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new AnnoLoader_Namespace_Map();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testNonDataProvided()
	{

	}

    public function dataProvider_testSetNamespaceLength()
    {
        return array
		(
          array(0, 0),
          array(1, 1),
          array(2, 2),
          array(3, 3),
        );
    }


	/**
     * @dataProvider dataProvider_testSetNamespaceLength
     */
	public function testGetSetNamespaceLength($namespaceLength, $expectedNamespaceLength)
	{
		$this->object->setNamespaceLength($namespaceLength);
		$this->assertEquals($expectedNamespaceLength, $this->object->getNamespaceLength());
	}

    public function dataProvider_testSetGetNamespaceMap()
    {
        return array
		(
          array('Ext.ex', 'Ext.ex'),
          array('Ext.ux', 'Ext.ux'),
          array('Ext', 'Ext'),
        );
    }


	/**
     * @dataProvider dataProvider_testSetGetNamespaceMap
     */
	public function testSetGetNamespaceMap($namespaceMap, $expectedNamespaceMap)
	{
		$this->object->setNamespaceMap($namespaceMap);
		$this->assertEquals($expectedNamespaceMap, $this->object->getNamespaceMap());
	}

    public function dataProvider_testGetNamespacePath()
    {
        return array
		(
          array('Ext.ex', 'lib/ex'),
          array('Ext.ux', 'lib/ux'),
        );
    }


	/**
     * @dataProvider dataProvider_testGetNamespacePath
     */
	public function testGetNamespacePath($namespace, $expectedNamespacePath)
	{
		$this->object = new AnnoLoader_Namespace_Map(array
		(
			'Ext.ex'	=> 'lib/ex',
			'Ext.ux'	=> 'lib/ux',
		));
		$this->assertEquals($expectedNamespacePath, $this->object->getNamespacePath($namespace));
	}

}

?>
