<?php

require_once 'PHPUnit/Framework.php';

require_once CLASS_PATH . '/AnnoLoader/Dependency/Type/Exception.php';
require_once CLASS_PATH . '/AnnoLoader/Dependency/Type/Abstract.php';
require_once CLASS_PATH . '/AnnoLoader/Dependency/Type/File.php';

/**
 * Test class for AnnoLoader_Dependency_Type_File.
 * Generated by PHPUnit on 2011-01-16 at 23:42:06.
 */
class AnnoLoader_Dependency_Type_FileTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Dependency_Type_File
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new AnnoLoader_Dependency_Type_File;

		$this->object->setFilesList(array
		(
			JS_PATH.'/DependencyTypeFile/1.js' => true,
			JS_PATH.'/DependencyTypeFile/2.js' => true,
		));

		$this->object->setBasePath(JS_PATH);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers AnnoLoader_Dependency_Type_File::getFiles
	 */
	public function testGetFiles()
	{
		$dependency = 'DependencyTypeFile/1.js';
		$this->assertEquals(array(JS_PATH.'/DependencyTypeFile/1.js'), $this->object->getFiles($dependency, 'test'));
		$dependency = 'DependencyTypeFile/2.js';
		$this->assertEquals(array(JS_PATH.'/DependencyTypeFile/2.js'), $this->object->getFiles($dependency, 'test'));
	}

	/**
	 * @covers AnnoLoader_Dependency_Type_File::getFiles
	 * @expectedException AnnoLoader_Dependency_Type_Exception
	 */
	public function testGetFilesException()
	{
		$dependency = 'DependencyTypeFile/nonExisting.js';
		$this->object->getFiles($dependency, 'test');
	}

}

?>
