<?php

require_once 'PHPUnit/Framework.php';

/**
 * Test class for AnnoLoader_Dependency_Type_Abstract.
 * Generated by PHPUnit on 2011-01-17 at 14:21:11.
 */
class AnnoLoader_Dependency_Type_AbstractTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Dependency_Type_Abstract
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new AnnoLoader_Dependency_Type_Abstract;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	public function testGetFiles()
	{
		$this->object->getFiles('', '');
	}

	public function testSetGetBasePath()
	{
		$basePath = 'basePath';
		$this->object->setBasePath($basePath);
		$this->assertEquals($basePath, $this->object->getBasePath());
	}

	public function testSetGetExtension()
	{
		$extension = 'extension';
		$this->object->setExtension($extension);
		$this->assertEquals($extension, $this->object->getExtension());
	}

	public function testSetGetNamespace()
	{
		$namespace = array
		(
			'Ext.ex'	=> '/ex/',
			'Ext.ux'	=> '/ux/',
		);
		$this->object->setNamespace($namespace);
		$this->assertEquals($namespace, $this->object->getNamespace());
	}

	public function testSetGetFileList()
	{
		$fileList = array
		(
			'/ex/data/Store.js'		=> true,
			'/ex/data/Record.js'	=> true,
			'/ex/grid/Panel.js'		=> true,
		);
		$this->object->setFilesList($fileList);
		$this->assertEquals($fileList, $this->object->getFilesList());
	}
}

?>
