<?php

require_once 'PHPUnit/Framework.php';

/**
 * Test class for AnnoLoader_Writer.
 * Generated by PHPUnit on 2011-01-18 at 18:41:21.
 */
class AnnoLoader_WriterTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Writer
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new AnnoLoader_Writer(array
		(
			JS_PATH.'/Writer/1.js',
			JS_PATH.'/Writer/2.js',
			JS_PATH.'/Writer/subdir/3.js',
		));
	}

	protected function tearDown() {

	}

	public function testAddGetFilter()
	{
		$this->object->addFilter(1);
		$this->assertEquals(array(1), $this->object->getFilters());

		$this->object->addFilter(2);
		$this->assertEquals(array(1,2), $this->object->getFilters());

		$this->object->addFilter(3);
		$this->assertEquals(array(1,2,3), $this->object->getFilters());
	}

	public function testWriteNoOutput()
	{
		$expectedResult = "Content of 1.js\nContent of 2.js\nContent of 3.js\n";
		$this->assertEquals($expectedResult, $this->object->write(false));
	}

}

?>
