<?php

require_once 'PHPUnit/Framework.php';

require_once CLASS_PATH.'/AnnoLoader/Dependency/Type/Directory/Single.php';
require_once CLASS_PATH.'/AnnoLoader/Dependency/Type/Exception.php';

/**
 * Test class for AnnoLoader_Dependency_Type_Directory_Single.
 * Generated by PHPUnit on 2011-01-17 at 13:40:23.
 */
class AnnoLoader_Dependency_Type_Directory_SingleTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AnnoLoader_Dependency_Type_Directory_Single
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new AnnoLoader_Dependency_Type_Directory_Single;

		$this->object->setFilesList(array
		(
			JS_PATH.'/DependencyTypeDirectory/1.js' => true,
			JS_PATH.'/DependencyTypeDirectory/2.js' => true,
			JS_PATH.'/DependencyTypeDirectory/subdir/4.js' => true,
		));

		$this->object->setBasePath(JS_PATH);
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {

	}

	/**
	 * @covers AnnoLoader_Dependency_Type_Directory_Single::getFiles
	 */
	public function testGetFiles()
	{
		$dependency = 'DependencyTypeDirectory';
		$this->assertEquals
		(
			array
			(
				JS_PATH.'/DependencyTypeDirectory/1.js',
				JS_PATH.'/DependencyTypeDirectory/2.js',
			),
			$this->object->getFiles($dependency, 'test')
		);
	}

	/**
	 * @covers AnnoLoader_Dependency_Type_Directory_Single::getFiles
	 * @expectedException AnnoLoader_Dependency_Type_Exception
	 */
	public function testGetFilesException()
	{
		$dependency = 'nonExistingDir';
		$this->object->getFiles($dependency, 'test');
	}

}

?>
